FileControllerNew
I need your help. I used your code to upload multipart file and insert into mongodb.

But I am getting error. 

I have save the code in this file. Please help.

Error:

i) getFiles()
Incompatible types.
Required:
java.util.List<com.mongodb.gridfs.GridFSDBFile>
Found: com.mongodb.client.gridfs.GridFSFindIterable

2) maybeLoadFile(String name)
Incompatible types.
Required:
com.mongodb.gridfs.GridFSDBFile
Found:
com.mongodb.client.gridfs.model.GridFSFile

3) gridFsTemplate.store(file.getInputStream(), name, file.getContentType()).save();
-- save() method is not in the list.Its throwing error.